INSERT INTO projects (title, category, funding_goal, start_date, end_date) Values ("Beach Cleanup","Ambient",40,"8/12/20","8/30/20" );
INSERT INTO projects (title, category, funding_goal, start_date, end_date) Values ("Food Drive", "Food",500,"8/13/20","8/20/20");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) Values ("Toys for Tots","Todlers",250, "8/13/20","8/15/20");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) Values ("Bake Sale","Food",300,"8/15/20","8/16/20");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) Values ("Tye-Dye Party","Event",200,"9/1/20","9/2/20");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) Values ("Chariy Auction","Event",300,"9/5/20","9/6/20");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) Values ("Coffe Drive","Food",200,"9/7/20","9/8/20");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) Values ("Community Class","Worshop",100,"9/10/20","9/13/20");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) Values ("Concert","Event",100,"9/14/20","9/15/20");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) Values ("Photo/Art Sale",40,"Art","9/16/20","9/20/20");

INSERT INTO users (name,age) VALUES ("text",0);
INSERT INTO users (name,age) VALUES ("text1", 1);
INSERT INTO users (name,age) VALUES ("text2", 2);
INSERT INTO users (name,age) VALUES ("text3",27);
INSERT INTO users (name,age) VALUES ("text4",40);
INSERT INTO users (name,age) VALUES ("text5", 16);
INSERT INTO users (name,age) VALUES ("text6", 30);
INSERT INTO users (name,age) VALUES ("text7", 69);
INSERT INTO users (name,age) VALUES ("text8", 40);
INSERT INTO users (name,age) VALUES ("text9", 35);
INSERT INTO users (name,age) VALUES ("text10", 26);
INSERT INTO users (name,age) VALUES ("text11", 42);
INSERT INTO users (name,age) VALUES ("text12", 34);
INSERT INTO users (name,age) VALUES ("text13", 68);
INSERT INTO users (name,age) VALUES ("text14", 35);
INSERT INTO users (name,age) VALUES ("text15", 44);
INSERT INTO users (name,age) VALUES ("text16", 20);
INSERT INTO users (name,age) VALUES ("text17", 26);
INSERT INTO users (name,age) VALUES ("text18", 39);
INSERT INTO users (name,age) VALUES ("text19", 52);

INSERT INTO pledges (amount, user_id, project_id) VALUES (19,1,3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (18,1,2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (17,2,1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (16,3,3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (15,3,4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (14,4,5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (13,5,6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (12,5,7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (11,6,8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10,6,9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (11,7,10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (12,7,9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (13,8,8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (14,8,7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (15,9,6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (16,10,5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (17,11,4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (18,12,3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (19,12,2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (18,13,1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (17,14,3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (16,15,4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (15,16,5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (14,17,6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (13,18,7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (12,19,8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (11,20,9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10,19,10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20,18,5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (21,17,4);